version: '3.8'
services:
  my-node-api-sqlite:
    image: my-node-api-sqlite
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - sqlite_data:/app/data   # persist the .db file
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/data/db.sqlite
    ports:
      - 3000:3000
volumes:
  sqlite_data:
    
